import type { GetStaticProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Authors from '../../../container/Authors';
import {
  defaultLoadPostVariables,
  loadPosts,
  RequestResponse,
} from '../../../data/load-posts';
import { PageProps } from '../../../Types/post';

export default function Author({ posts, mount, letter, variables }: PageProps) {
  const router = useRouter();
  if (router.isFallback) {
    return <h1>Loading</h1>;
  }
  return (
    <div>
      <Head>
        <title>The Scions Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Authors
        posts={posts}
        mount={mount}
        letter={letter}
        variables={variables}
      />
    </div>
  );
}

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps<RequestResponse> = async (ctx) => {
  console.log(ctx.params);
  if (!ctx.params || !ctx.params.param) {
    return {
      notFound: true,
    };
  }

  const page = Number(ctx.params.param[1]);
  const limit = 2;
  const start = (page - 1) * limit;
  const nextPage = page + 1;
  const previousPage = page - 1;

  let data = null;
  try {
    data = await loadPosts({
      authorSlug: {
        eq: ctx.params.param[0] as string,
      },
      start: start,
      limit: limit,
    });
  } catch (e) {
    data = null;
  }

  let mount = null;
  try {
    mount = await loadPosts({
      tagSlug: {
        contains: 'mount' as string,
      },
    });
  } catch (e) {
    mount = null;
  }

  let letter = null;
  try {
    letter = await loadPosts({
      tagSlug: {
        contains: 'live-letter' as string,
      },
    });
  } catch (e) {
    letter = null;
  }
  if (
    !data ||
    !letter ||
    !mount ||
    !data.posts ||
    !mount.posts ||
    !data.posts.data.length ||
    !mount.posts.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts: data.posts,
      mount: mount.posts.data[0],
      letter: letter.posts.data[0],
      variables: {
        ...defaultLoadPostVariables,
      },
    },
    revalidate: 24 * 60 * 60,
  };
};
