import type { GetStaticProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import FilteredPosts from '../../../container/FilteredPosts';
import Skeleton from '../../../container/FilteredPosts/skeleton';
import { loadPosts, RequestResponse } from '../../../data/load-posts';
import { PageProps } from '../../../Types/post';

export default function ExpansionPage({
  posts,
  mount,
  letter,
  param,
  nextPage,
  previousPage,
  postsPerPage,
  numberOfPosts,
}: PageProps) {
  const router = useRouter();
  if (router.isFallback) {
    return <Skeleton />;
  }

  const post = posts.data[0].attributes.category.data.attributes.name;
  return (
    <div>
      <Head>
        <title>The Scions Report - {post}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FilteredPosts
        numberOfPosts={numberOfPosts}
        nextPage={nextPage}
        previousPage={previousPage}
        param={param}
        route={'posts'}
        posts={posts}
        mount={mount}
        letter={letter}
        postsPerPage={postsPerPage}
      />
    </div>
  );
}

export const getStaticProps: GetStaticProps<RequestResponse> = async () => {
  let data = null;
  try {
    data = await loadPosts();
  } catch (e) {
    data = null;
  }

  let mount = null;
  try {
    mount = await loadPosts({
      tagSlug: {
        eq: 'mounts' as string,
      },
    });
  } catch (e) {
    mount = null;
  }

  let letter = null;
  try {
    letter = await loadPosts({
      tagSlug: {
        eq: 'live-letter' as string,
      },
    });
  } catch (e) {
    letter = null;
    console.log(e);
  }
  if (
    !data ||
    !letter ||
    !mount ||
    !data.posts ||
    !mount.posts ||
    !data.posts.data.length ||
    !mount.posts.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts: data.posts,
      mount: mount.posts.data[0],
      letter: letter.posts.data[0],
    },
    revalidate: 24 * 60 * 60,
  };
};
