import type { GetStaticProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import AuthorSkeleton from '../container/FilteredPosts/skeleton';
import Post from '../container/Post';
import { loadPosts, RequestResponse } from '../data/load-posts';
import { PostPageTypes } from '../Types/post';

export default function PostPage({ posts, mount, letter }: PostPageTypes) {
  const router = useRouter();
  if (router.isFallback) {
    return <AuthorSkeleton />;
  }
  const post = posts.data[0].attributes;
  return (
    <div>
      <Head>
        <title>The Scions Report - {post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post post={post} mount={mount} letter={letter} />
    </div>
  );
}

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps<RequestResponse> = async (ctx) => {
  if (!ctx.params || !ctx.params.param) {
    return {
      notFound: true,
    };
  }

  const post = ctx.params.param[1];

  let data = null;
  try {
    data = await loadPosts({
      postSlug: {
        eq: post as string,
      },
    });
  } catch (e) {
    data = null;
  }

  let mount = null;
  try {
    mount = await loadPosts({
      tagSlug: {
        contains: 'mount' as string,
      },
    });
  } catch (e) {
    mount = null;
  }

  let letter = null;
  try {
    letter = await loadPosts({
      tagSlug: {
        contains: 'live-letter' as string,
      },
    });
  } catch (e) {
    letter = null;
  }
  if (
    !data ||
    !letter ||
    !mount ||
    !data.posts ||
    !mount.posts ||
    !data.posts.data.length ||
    !mount.posts.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts: data.posts,
      mount: mount.posts.data[0],
      letter: letter.posts.data[0],
    },
    revalidate: 24 * 60 * 60,
  };
};
