import type { GetStaticProps } from 'next';
import Head from 'next/head';
import HomePage from '../container/HomePage';
import { loadPosts, RequestResponse } from '../data/load-posts';
import { FullPost, PostObject } from '../Types/post';

export type HomeProps = {
  mainPosts: FullPost;
  posts: FullPost;
  mount: PostObject;
  letter: PostObject;
};

export default function Home({ posts, mainPosts, mount, letter }: HomeProps) {
  return (
    <div>
      <Head>
        <title>The Scions Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage
        posts={posts}
        mainPosts={mainPosts}
        mount={mount}
        letter={letter}
      />
    </div>
  );
}

export const getStaticProps: GetStaticProps<RequestResponse> = async () => {
  let data = null;
  try {
    data = await loadPosts({
      start: 0,
      limit: 2,
    });
  } catch (e) {
    data = null;
  }

  let postData = null;
  try {
    postData = await loadPosts({
      start: 2,
    });
  } catch (e) {
    postData = null;
  }

  let mount = null;
  try {
    mount = await loadPosts({
      tagSlug: {
        contains: 'mounts' as string,
      },
    });
  } catch (e) {
    mount = null;
  }

  let letter = null;
  try {
    letter = await loadPosts({
      tagSlug: {
        contains: 'live-letter' as string,
      },
    });
  } catch (e) {
    letter = null;
  }
  if (
    !data ||
    !postData ||
    !letter ||
    !mount ||
    !data.posts ||
    !mount.posts ||
    !data.posts.data.length ||
    !postData.posts.data.length ||
    !mount.posts.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts: postData.posts,
      mainPosts: data.posts,
      mount: mount.posts.data[0],
      letter: letter.posts.data[0],
    },
    revalidate: 24 * 60 * 60,
  };
};
