import type { GetStaticProps } from 'next';
import Head from 'next/head';
import HomePage from '../container/HomePage';
import { loadPosts, RequestResponse } from '../data/load-posts';
import { FullPost } from '../Types/post';

export type HomeProps = {
  posts: FullPost;
};

export default function Home({ posts }: HomeProps) {
  return (
    <div>
      <Head>
        <title>The Scions Report</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage posts={posts} />
    </div>
  );
}
//<Homepage posts={posts} categories={categories} />

export const getStaticProps: GetStaticProps<
  RequestResponse // |RequestCategoryResponse
> = async () => {
  let data = null;
  try {
    data = await loadPosts();
  } catch (e) {
    data = null;
  }
  //const sprout = null;
  //const dataCategory = null;
  // try {
  //   dataCategory = await loadCategories();
  // } catch (e) {
  //   dataCategory = null;
  // }
  if (
    !data ||
    //!dataCategory ||
    !data.posts ||
    //!dataCategory.categories ||
    !data.posts.data.length //||
    //!dataCategory.categories.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: { posts: data.posts /*,categories: dataCategory.categories*/ },
    revalidate: 24 * 60 * 60,
  };
};
