import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Skeleton from '../../container/Posts/components/skeleton';
import { loadPosts, RequestResponse } from '../../data/load-posts';
import { PageProps } from '../../Types/post';
import Posts from '../../container/Posts';

export default function PostsPage({ posts, mount, letter }: PageProps) {
  const router = useRouter();
  if (router.isFallback) {
    return <Skeleton />;
  }

  return (
    <div>
      <Head>
        <title>The Scions Report - Pesquisa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Posts posts={posts} mount={mount} letter={letter} filter={true} />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<RequestResponse> = async (
  ctx,
) => {
  let data = null;
  const query = ctx.query.q || '';
  try {
    data = await loadPosts({
      postSearch: {
        contains: query as string,
      },
    });
  } catch (e) {
    data = null;
  }

  let mount = null;
  try {
    mount = await loadPosts({
      tagSlug: {
        eq: 'mounts' as string,
      },
    });
  } catch (e) {
    mount = null;
  }

  let letter = null;
  try {
    letter = await loadPosts({
      tagSlug: {
        eq: 'live-letter' as string,
      },
    });
  } catch (e) {
    letter = null;
    console.log(e);
  }
  if (
    !data ||
    !letter ||
    !mount ||
    !data.posts ||
    !mount.posts ||
    !data.posts.data.length ||
    !mount.posts.data.length
  ) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts: data.posts,
      mount: mount.posts.data[0],
      letter: letter.posts.data[0],
    },
  };
};
